name: delete-older-releases
on:
  workflow_dispatch:
#  schedule:
#    - cron: 0 16 * * *
    
jobs:
  del_runs:
    runs-on: ubuntu-20.04
    steps:
    
    - name: 删除工作流
      uses: GitRML/delete-workflow-runs@main
      with:
        #retain_days: 1
        keep_minimum_runs: 1
    
    - name: 清理releases
      continue-on-error: true
      if: env.REPO_TOKEN
      uses: ophub/delete-releases-workflows@main
      with:
        delete_releases: true
      #releases_keep_keyword: targz/Update
        releases_keep_latest: 1
        delete_tags: true
        delete_workflows: true
        workflows_keep_day: 7
        #gh_token: ${{ secrets.REPO_TOKEN }}
